---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
  - name: test
    run_list:
       - recipe[config_newrelic::test]
       - recipe[config_newrelic::default]
    
    attributes:
       
